- hosts: localhost
  gather_facts: no

  vars:
    dict_variable:
      a: one
      b: two
      c: three

  tasks:
    - debug:
        msg: "{{ lookup('dict', dict_variable, wantlist=True) }}"

    - debug:
        msg: "{{ q('dict', dict_variable) }}"

