version: 3

images:
  base_image:
    name: almalinux:8

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  galaxy:
    collections:
      - name: community.postgresql
