- hosts: webservers
  gather_facts: no

  tasks:
    - name: Install the package jq, tool for JSON like sed for text
      ansible.builtin.package:
        name: jq
        state: present

    - name: Create directory for ansible custom facts
      ansible.builtin.file:
        state: directory
        recurse: true
        path: /etc/ansible/facts.d

    - name: Install custom ipmi fact
      ansible.builtin.copy:
        src: ipmi.fact
        mode: '0755'
        dest: /etc/ansible/facts.d

    - name: Re-read facts after adding custom fact
      ansible.builtin.setup:
        filter: ansible_local

    - name: Show ansible_local
      debug:
        msg: "{{ ansible_local['ipmi'] }}"
