- hosts: webservers
  gather_facts: no

  vars:
    favcolor: blue
  vars_files:
    - /tmp/external_vars.yml

  tasks:

    - name: This is just a placeholder
      ansible.builtin.command: /bin/echo foo
      register: foo_result

    - debug:
        msg: "{{ password }}"
