---
- name: Error handling tests
  hosts: db
  gather_facts: no
  vars:

  tasks:
    - name: Combine multiple conditions to override 'changed' result
      ansible.builtin.command: /bin/fake_command
      register: result
      ignore_errors: True
      changed_when:
        - '"ERROR" in result.stderr'
        - result.rc == 2
