---
- hosts: db
  gather_facts: no
  vars:
    bar_status:
      rc: 127


  tasks:
    - name: check value of return code
      ansible.builtin.debug:
        var: bar_status.rc

    - name: check test for rc value as string
      ansible.builtin.debug:
        var: bar_status.rc == "127"

    - name: check test for rc value as integer
      ansible.builtin.debug:
        var: bar_status.rc == 127
