---
- hosts: db
  gather_facts: no
  vars:

  tasks:
    - name: Gather facts from app servers
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['app'] }}"

    - name: Lookup `hostvars`
      debug:
        msg: "{{ hostvars['almalinux-207']['ansible_default_ipv4']['address'] }}"
