- name: Continue executing when a failure occurs
  gather_facts: no
  hosts: nginx
  vars:

  tasks:
    - name: The same as above using a dict
      ansible.builtin.command: echo {{ item.key }}
      loop: "{{ query('dict', mydict|default({})) }}"
      when: item.value > 5
