---
- name: Test filters
  hosts: nginx
  gather_facts: False
  vars:

  tasks:
    - name: Prepare JSON file
      template:
        src: /home/hector/ansible-tutorial/src/usage/playbook/using/domain_definition.json
        dest: /home/hector/domain_definition.json
