---
- hosts: nginx,db
  gather_facts: no
  vars:

  tasks:
      - setup:
          gather_subset:
            - distribution_major_version

      - name: Get the CPU temperature
        set_fact:
          temperature: "{{ ansible_facts['distribution_major_version'] }}"

      - name: Restart the system if the temperature is too high
        # shell: "reboot"
        debug:
          msg: "{{ temperature }}"
        when: temperature | float >= 9
