---
- name: Test filters
  hosts: nginx
  gather_facts: False
  vars:
    domain_definition: "{{ lookup('file', '../using/domain_definition.json') | from_json }}"

  tasks:
    - name: Gen random MAC addresses
      ansible.builtin.debug:
        msg: "{{ '52:54:00' | community.general.random_mac(seed=inventory_hostname) }}"
