---
- name: Loop tests
  hosts: nginx
  gather_facts: no
  vars:
    my_list:
      - 11
      - this
      - 12
      - that

  tasks:
    - name: with_random_choice
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_random_choice: "{{ my_list }}"

    - name: with_random_choice -> loop (No loop is needed here)
      ansible.builtin.debug:
        msg: "{{ my_list|random }}"
      tags: random
