---
- name: Test filters
  hosts: nginx
  gather_facts: False
  vars:

  tasks:
    - name: Generate multiple hostnames
      ansible.builtin.debug:
        msg: "{{ ['foo', 'bar'] | product(['com']) | map('join', '.') | join(',') }}"
