---
- name: Test filters
  hosts: nginx
  gather_facts: False
  vars:
    b64hector: "{{ '彭海林' | string | b64encode }}"
    string: "unisko@gmail.com"

  tasks:
    - name: Gathering mounts
      setup:
        gather_subset:
          - distribution
          - mounts

    - name: Get a comma-separated list of the mount points
      debug:
        # msg: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"
        msg: "{{ '%H:%M:%S' | strftime(utc=True) }}"
