---
- name: Test filters
  hosts: nginx
  gather_facts: False
  vars:
    demo_xml: "{{ lookup('file', '../demo_output.xml') }}"

  tasks:
    - name: Gen random MAC addresses
      ansible.builtin.debug:
        msg: "{{ demo_xml | ansible.netcommon.parse_xml('/home/hector/ansible-tutorial/src/usage/playbook/demo_spec.yaml') }}"
