- name: Check registered variable for emptiness
  hosts: all

  tasks:
      - file:
          path: '/home/hector/mydir'
          state: directory

      - name: List contents of directory
        ansible.builtin.command: 'ls mydir'
        register: contents

      - name: Check contents for emptiness
        ansible.builtin.debug:
          msg: "Directory is empty"
        when: contents.stdout == ""
