---
- name: Verify nginx installation
  gather_facts: no
  hosts: webservers
  vars:
    www_service: web
    kv_service: memcached

  tasks:
    - setup:
        gather_subset:
          - distribution

    - name: Set host variables based on distribution
      include_vars: "{{ ansible_facts.distribution }}.yml"

    - name: Update nginx config
      ansible.builtin.template:
        src: './templates/nginx.j2'
        dest: '/etc/nginx/nginx.conf'
      notify:
        - 'Restart web service'
        - 'restart memcached service'

  handlers:
    - name: 'Restart {{ www_service }} service'
      ansible.builtin.service:
        name: "{{ web_service_name | default('nginx') }}"
        state: restarted

    - name: 'Restart memcached service'
      ansible.builtin.service:
        name: memcached
        state: restarted
      listen: 'restart memcached service'
