---
- name: Verify nginx installation
  gather_facts: no
  hosts: webservers
  vars:
    http_port: 80
    max_clients: 256

  tasks:
    - name: Copy nginx configuration
      ansible.builtin.template:
        src: /srv/nginx.j2
        dest: /etc/nginx/nginx.conf
      # The task is always reported as changed
      changed_when: True
      notify: Restart nginx

  handlers:
    - name: Restart memcached
      service:
        name: memcached
        state: restarted
      listen: "restart web services"

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      listen: "restart web services"
