---
- name: Data manipulating
  gather_facts: yes
  hosts: all

  tasks:
    - name: Get the unique list of values of a variable that vary per host
      ansible.builtin.debug:
        msg: "{{ unique_value_list }}"
      vars:
        unique_value_list: "{{ groups['all'] | map('extract', hostvars, 'varname') | list | unique }}"
