- hosts: webservers
  gather_facts: no

  tasks:
    - name: Run a command as nobody
      command: nginx -t
      become: true
      become_method: su
      become_user: nobody
      become_flags: '-s /bin/sh'
