- hosts: webservers
  gather_facts: no

  tasks:
    - name: Ensure the nginx service is running
      service:
        name: nginx
        state: started
      become: true

    - name: Run a command as the nginx user
      command: nginx -t
      become: true
      become_user: nginx
