win_servers:
  hosts:
    win10-133:
      ansible_host: 192.168.122.133
      ansible_user: 'Hector PENG'
      ansible_ssh_pass: '091517'
    win2k19-151:
      ansible_host: 192.168.122.151
      ansible_user: 'Administrator'
      ansible_ssh_pass: '5yw69dUE'
  vars:
    become_method: runas
    ansible_shell_type: powershell
    ansible_connection: psrp
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
    ansible_winrm_message_encryption: always

dbservers:
  hosts:
    almalinux-39:
      ansible_host: 192.168.122.39
    freebsd-14:
      ansible_host: 192.168.122.181
      ansible_python_interpreter: /usr/local/bin/python
      ansible_connection: ssh
      ansible_become: true
      ansible_become_user: root
      ansible_become_method: sudo
      ansible_interpreter_python_fallback: ['/usr/local/bin/python', '/usr/local/bin/python3', '/usr/local/bin/python3.11']
      ansible_perl_interpreter: /usr/local/bin/perl

  vars:
      db_port: 5432

webservers:
  hosts:
    almalinux-5:
      ansible_host: 192.168.122.5
    almalinux-61:
      ansible_host: 192.168.122.61

  vars:
    http_port: 443

lbservers:
  hosts:
    debian-199:
      ansible_host: 192.168.122.199

fileservers:
  hosts:
    debian-199:
      ansible_host: 192.168.122.199

monitoring:
  hosts:
    almalinux-207:
      ansible_host: 192.168.122.207

facility:
  children:
    dbservers:
    lbservers:
    monitoring:

website:
  children:
    facility:
    webservers:
  vars:
    ansible_user: hector
    ansible_python_interpreter: auto_silent
