---
- name: configure cisco routers
  hosts: cisco-r1
  gather_facts: no
  vars:
    dns: "223.5.5.5 223.6.6.6"

  tasks:
   - name: configure hostname
     cisco.ios.ios_config:
       lines: hostname {{ inventory_hostname }}

   - name: configure DNS
     cisco.ios.ios_config:
       lines: ip name-server {{ dns }}
