---
- hosts: nxos-sw
  gather_facts: false

  tasks:
  - name: "Fetch interface state and parse with pyats"
    ansible.utils.cli_parse:
      command: show interface
      parser:
        name: ansible.netcommon.pyats
    register: nxos_pyats_show_interface

  - name: Validate interface admin state
    ansible.utils.validate:
      data: "{{ nxos_pyats_show_interface['parsed'] }}"
      criteria:
        - "{{ lookup('file',  './criteria/nxos_show_interface_admin_criteria.json') | from_json }}"
      engine: ansible.utils.jsonschema
    ignore_errors: true
    register: res

  - name: Print the interface names that do not satisfy the desired state
    ansible.builtin.debug:
      msg: "{{ item['data_path'].split('.')[0] }}"
    loop: "{{ res['errors'] }}"
    when: "'errors' in res"
