---
- hosts: nxos-sw
  gather_facts: no

  tasks:
    - name: "Run command and parse with textfsm"
      ansible.utils.cli_parse:
        command: show interface
        parser:
          name: ansible.utils.textfsm
        set_fact: interfaces

    - debug:
        msg: "{{ interfaces }}"
