---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: vyos-r1
  tasks:

    - name: Get config for VyOS devices
      vyos.vyos.vyos_facts:
        gather_subset:
          - default
          - config

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
